### ISSUE TITLE
Error 404 with LDAP Users and Favorites folder

### ISSUE THREAD

**Issue by sebabordon** [nextcloud/ios#200]
iOS app version: v2.17
Nextcloud version : 11.0.3
Operating system and version Debian 8
nginx 
PHP 5.6
Is this the first time you've seen this error?:
Yes

Can you reliably replicate it? (If so, please outline steps):
Configure LDAP to Active Directory
Login to the server
Install IOS App.
Add an LDAP account in iOS
Mark a folder as Favorite:
- Error Request not found (404) appears

The issue you are facing:
I receive error "Request Not Found (404)" when marking a folder as favorite in iOS app 2.17. Didn't happened with the previous app version and it does not happens with with local users.

The output of your Nextcloud log in Admin > Logging:

 {"reqId":"XfbnVGMqVkbOzvlYR8t9","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login attempt: \"seba\"","level":1,"time":"2017-04-25T13:32:01+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Fotos","user":"--","version":"11.0.3.2"}
{"reqId":"XfbnVGMqVkbOzvlYR8t9","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login successful: \"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715\"","level":1,"time":"2017-04-25T13:32:01+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Fotos","user":"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715","version":"11.0.3.2"}
{"reqId":"xl+sjGr0JrQeesS1E1s0","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login attempt: \"seba\"","level":1,"time":"2017-04-25T13:32:01+00:00","method":"GET","url":"\/ocs\/v1.php\/cloud\/capabilities?format=json","user":"--","version":"11.0.3.2"}
{"reqId":"2luyHToxkbqnwl2jGfxQ","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login attempt: \"seba\"","level":1,"time":"2017-04-25T13:32:01+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications?format=json","user":"--","version":"11.0.3.2"}
{"reqId":"xl+sjGr0JrQeesS1E1s0","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login successful: \"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715\"","level":1,"time":"2017-04-25T13:32:01+00:00","method":"GET","url":"\/ocs\/v1.php\/cloud\/capabilities?format=json","user":"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715","version":"11.0.3.2"}
{"reqId":"2luyHToxkbqnwl2jGfxQ","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login successful: \"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715\"","level":1,"time":"2017-04-25T13:32:01+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications?format=json","user":"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715","version":"11.0.3.2"}
{"reqId":"ILTz7no7ij86z\/a18g+s","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login attempt: \"seba\"","level":1,"time":"2017-04-25T13:32:01+00:00","method":"GET","url":"\/ocs\/v1.php\/cloud\/users\/seba?format=json","user":"--","version":"11.0.3.2"}
{"reqId":"ILTz7no7ij86z\/a18g+s","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login successful: \"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715\"","level":1,"time":"2017-04-25T13:32:01+00:00","method":"GET","url":"\/ocs\/v1.php\/cloud\/users\/seba?format=json","user":"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715","version":"11.0.3.2"}
{"reqId":"ILTz7no7ij86z\/a18g+s","remoteAddr":"xx.x.x.x","app":"user_ldap","message":"No DN found for seba on ldaps:\/\/ss.ss.xxx.xxx","level":0,"time":"2017-04-25T13:32:01+00:00","method":"GET","url":"\/ocs\/v1.php\/cloud\/users\/seba?format=json","user":"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715","version":"11.0.3.2"}
{"reqId":"Auv728Nc103AY08WqOAJ","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login attempt: \"seba\"","level":1,"time":"2017-04-25T13:32:01+00:00","method":"GET","url":"\/ocs\/v2.php\/cloud\/activity?format=json","user":"--","version":"11.0.3.2"}
{"reqId":"Auv728Nc103AY08WqOAJ","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login successful: \"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715\"","level":1,"time":"2017-04-25T13:32:01+00:00","method":"GET","url":"\/ocs\/v2.php\/cloud\/activity?format=json","user":"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715","version":"11.0.3.2"}
{"reqId":"yD8Lnyoo9fn8sLoYXibw","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login attempt: \"seba\"","level":1,"time":"2017-04-25T13:32:02+00:00","method":"REPORT","url":"\/remote.php\/dav\/files\/seba","user":"--","version":"11.0.3.2"}
{"reqId":"yD8Lnyoo9fn8sLoYXibw","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login successful: \"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715\"","level":1,"time":"2017-04-25T13:32:02+00:00","method":"REPORT","url":"\/remote.php\/dav\/files\/seba","user":"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715","version":"11.0.3.2"}
{"reqId":"yD8Lnyoo9fn8sLoYXibw","remoteAddr":"xx.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 Principal with name seba not found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): Sabre\\\\DAVACL\\\\AbstractPrincipalCollection->getChild('seba')\\n#1 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/FilesReportPlugin.php(171): Sabre\\\\DAV\\\\Tree->getNodeForPath('files\\\/seba')\\n#2 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\FilesReportPlugin->onReport('{http:\\\/\\\/ownclou...', Array, 'files\\\/seba')\\n#3 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(718): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#8 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(231): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/remote.php(165): require_once('\\\/media\\\/9ef19a91...')\\n#12 {main}\",\"File\":\"\\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/AbstractPrincipalCollection.php\",\"Line\":118,\"User\":\"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715\"}","level":0,"time":"2017-04-25T13:32:02+00:00","method":"REPORT","url":"\/remote.php\/dav\/files\/seba","user":"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715","version":"11.0.3.2"}
{"reqId":"VgzkAyZZAKIiydrKw+NJ","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login attempt: \"seba\"","level":1,"time":"2017-04-25T13:32:02+00:00","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares","user":"--","version":"11.0.3.2"}
{"reqId":"VgzkAyZZAKIiydrKw+NJ","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login successful: \"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715\"","level":1,"time":"2017-04-25T13:32:02+00:00","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares","user":"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715","version":"11.0.3.2"}
{"reqId":"rLdm3mx9NPL\/TIFYwG6h","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login attempt: \"seba\"","level":1,"time":"2017-04-25T13:32:11+00:00","method":"PROPPATCH","url":"\/remote.php\/dav\/files\/seba\/Documentos","user":"--","version":"11.0.3.2"}
{"reqId":"rLdm3mx9NPL\/TIFYwG6h","remoteAddr":"xx.x.x.x","app":"admin_audit","message":"Login successful: \"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715\"","level":1,"time":"2017-04-25T13:32:11+00:00","method":"PROPPATCH","url":"\/remote.php\/dav\/files\/seba\/Documentos","user":"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715","version":"11.0.3.2"}
{"reqId":"rLdm3mx9NPL\/TIFYwG6h","remoteAddr":"xx.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 Principal with name seba not found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): Sabre\\\\DAVACL\\\\AbstractPrincipalCollection->getChild('seba')\\n#1 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(71): Sabre\\\\DAV\\\\Tree->getNodeForPath('files\\\/seba')\\n#2 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(770): Sabre\\\\DAV\\\\Tree->getNodeForPath('files\\\/seba\\\/Docu...')\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->propPatchNodeUpdate('files\\\/seba\\\/Docu...', Object(Sabre\\\\DAV\\\\PropPatch))\\n#4 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1241): Sabre\\\\Event\\\\EventEmitter->emit('propPatch', Array)\\n#6 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(385): Sabre\\\\DAV\\\\Server->updateProperties('files\\\/seba\\\/Docu...', Array)\\n#7 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropPatch(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#9 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPPATC...', Array)\\n#10 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(231): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#13 \\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/remote.php(165): require_once('\\\/media\\\/9ef19a91...')\\n#14 {main}\",\"File\":\"\\\/media\\\/9ef19a91-e620-4630-8472-c536435bc9c7\\\/Nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/AbstractPrincipalCollection.php\",\"Line\":118,\"User\":\"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715\"}","level":0,"time":"2017-04-25T13:32:11+00:00","method":"PROPPATCH","url":"\/remote.php\/dav\/files\/seba\/Documentos","user":"F719F8A6-EFE5-4719-AC01-2718D2B5CEB6_5715","version":"11.0.3.2"}

**Comment by sebabordon** [comment]
I had to redo the entire LDAP to Active Directory configuration, clear user mappings from scratch and now it's working. As a comment, I've tested the OC app to nextcloud and downloads where working with the previous configuration.
